apiVersion: v1
kind: Service
metadata:
  name: simple-deployment
  namespace: contrailtest
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    svc: beaker-web-deployment
